spring:
  application:
    name: config-server
  cloud:
    # 配置文件的远程仓库
    config:
      label: master
      server:
        git:
#          uri: https://github.com/how2j/springcloudConfig/
          uri: https://gitee.com/techrice/config/
          searchPaths: respo

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
